# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: events.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto


class CombatMetadataKind(betterproto.Enum):
    unknown = 0
    physical = 1
    magic = 2
    environmental = 3


class HealingMetadataKind(betterproto.Enum):
    unknown = 0
    direct = 1
    over_time = 2


@dataclass
class Event(betterproto.Message):
    created: datetime = betterproto.message_field(1)
    event_timestamp: datetime = betterproto.message_field(2)
    client: str = betterproto.string_field(3)
    combat: "CombatMetadata" = betterproto.message_field(4, group="metadata")
    healing: "HealingMetadata" = betterproto.message_field(5, group="metadata")
    support: "SupportMetadata" = betterproto.message_field(6, group="metadata")
    group: "GroupMetadata" = betterproto.message_field(7, group="metadata")


@dataclass
class GroupMetadata(betterproto.Message):
    source: str = betterproto.string_field(1)
    msg: str = betterproto.string_field(2)


@dataclass
class CombatMetadata(betterproto.Message):
    source: str = betterproto.string_field(1)
    target: str = betterproto.string_field(2)
    action: str = betterproto.string_field(3)
    kind: "CombatMetadataKind" = betterproto.enum_field(4)
    amount: int = betterproto.int64_field(5)
    success: bool = betterproto.bool_field(6)
    modifiers: List[str] = betterproto.string_field(7)


@dataclass
class HealingMetadata(betterproto.Message):
    source: str = betterproto.string_field(1)
    target: str = betterproto.string_field(2)
    action: str = betterproto.string_field(3)
    kind: "HealingMetadataKind" = betterproto.enum_field(4)
    amount: int = betterproto.int64_field(5)
    succes: bool = betterproto.bool_field(6)
    partial: bool = betterproto.bool_field(7)
    modifiers: List[str] = betterproto.string_field(8)


@dataclass
class SupportMetadata(betterproto.Message):
    source: str = betterproto.string_field(1)
    target: str = betterproto.string_field(2)
    action: str = betterproto.string_field(3)
